import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import asyncio
from sqlalchemy import text
from src.database.session import engine

async def run_migrations():
    statements = [
        "ALTER TABLE erp_inventory_batches ADD COLUMN IF NOT EXISTS uom VARCHAR(50) DEFAULT 'Pcs';",
        "ALTER TABLE erp_inventory_batches ADD COLUMN IF NOT EXISTS cost_price NUMERIC(15, 2) DEFAULT 0.0;",
        "ALTER TABLE erp_inventory_batches ADD COLUMN IF NOT EXISTS mrp NUMERIC(15, 2) DEFAULT 0.0;",
        "ALTER TABLE erp_inventory_batches ADD COLUMN IF NOT EXISTS selling_price NUMERIC(15, 2) DEFAULT 0.0;",
        "ALTER TABLE erp_inventory_batches ADD COLUMN IF NOT EXISTS tax_percent NUMERIC(5, 2) DEFAULT 0.0;",
        "ALTER TABLE erp_inventory_batches ADD COLUMN IF NOT EXISTS location VARCHAR(150);",
        "ALTER TABLE erp_inventory_batches ADD COLUMN IF NOT EXISTS supplier_invoice_no VARCHAR(100);",
        "ALTER TABLE erp_inventory_batches ADD COLUMN IF NOT EXISTS qc_status VARCHAR(50) DEFAULT 'Passed';",
        "ALTER TABLE erp_inventory_batches ADD COLUMN IF NOT EXISTS barcode VARCHAR(100);",
        "ALTER TABLE erp_brands ADD COLUMN IF NOT EXISTS image_url VARCHAR(1024);",
        "ALTER TABLE erp_brands ADD COLUMN IF NOT EXISTS category VARCHAR(100);",
        "ALTER TABLE erp_brands ADD COLUMN IF NOT EXISTS manufacturer VARCHAR(150);",
        "ALTER TABLE erp_brands ADD COLUMN IF NOT EXISTS description TEXT;",
        "ALTER TABLE erp_product_categories ADD COLUMN IF NOT EXISTS image_url VARCHAR(1024);",
        "ALTER TABLE erp_product_categories ADD COLUMN IF NOT EXISTS icon VARCHAR(50);",
        "ALTER TABLE erp_product_categories ADD COLUMN IF NOT EXISTS parent_id UUID;",
        "ALTER TABLE erp_uoms ADD COLUMN IF NOT EXISTS unit_type VARCHAR(50);",
        "ALTER TABLE erp_uoms ADD COLUMN IF NOT EXISTS base_unit BOOLEAN DEFAULT FALSE;",
        "ALTER TABLE erp_uoms ADD COLUMN IF NOT EXISTS conversion_rate FLOAT DEFAULT 1.0;",
        "ALTER TABLE erp_uoms ADD COLUMN IF NOT EXISTS unit_symbol VARCHAR(20);",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS initial_stock INTEGER DEFAULT 0;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS on_hand_stock INTEGER DEFAULT 0;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS reserved_stock INTEGER DEFAULT 0;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS online_price NUMERIC(10, 2) DEFAULT 0.0;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS store_price NUMERIC(10, 2) DEFAULT 0.0;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS rack_location VARCHAR(100);",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS reorder_level INTEGER DEFAULT 0;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS safety_stock INTEGER DEFAULT 0;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS purchase_price NUMERIC(10, 2) DEFAULT 0.0;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS mrp NUMERIC(10, 2) DEFAULT 0.0;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS selling_price NUMERIC(10, 2) DEFAULT 0.0;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS wholesale_price NUMERIC(10, 2) DEFAULT 0;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS b2b_price NUMERIC(10, 2) DEFAULT 0;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS min_wholesale_qty INTEGER DEFAULT 1;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS tax_percent NUMERIC(5, 2) DEFAULT 0.0;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS is_tax_inclusive BOOLEAN DEFAULT TRUE;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS discount_limit NUMERIC(5, 2) DEFAULT 0.0;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS supplier VARCHAR(150);",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS warehouse VARCHAR(150);",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS specifications JSONB DEFAULT '{}'::jsonb;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS base_name VARCHAR(150);",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS product_base_code VARCHAR(100);",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS size_l_kg VARCHAR(50);",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS image_url TEXT;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS short_description TEXT;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS long_description TEXT;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS hsn_code VARCHAR(100);",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS category_id UUID REFERENCES erp_product_categories(id) ON DELETE SET NULL;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS brand_id UUID REFERENCES erp_brands(id) ON DELETE SET NULL;",
        "ALTER TABLE erp_products ADD COLUMN IF NOT EXISTS uom_id UUID REFERENCES erp_uoms(id) ON DELETE SET NULL;",
        "ALTER TABLE erp_master_catalog ADD COLUMN IF NOT EXISTS specifications TEXT;",
        "ALTER TABLE employees ADD COLUMN IF NOT EXISTS sales_points NUMERIC(12, 2) DEFAULT 0.0;",
        "ALTER TABLE crm_customers ADD COLUMN IF NOT EXISTS alternate_phone VARCHAR(100);",
        "ALTER TABLE crm_customers ADD COLUMN IF NOT EXISTS whatsapp_number VARCHAR(100);",
        "ALTER TABLE crm_customers ADD COLUMN IF NOT EXISTS contact_person VARCHAR(255);",
        "ALTER TABLE crm_customers ADD COLUMN IF NOT EXISTS city VARCHAR(100);",
        "ALTER TABLE crm_customers ADD COLUMN IF NOT EXISTS state VARCHAR(100);",
        "ALTER TABLE crm_customers ADD COLUMN IF NOT EXISTS country VARCHAR(100) DEFAULT 'India';",
        "ALTER TABLE crm_customers ADD COLUMN IF NOT EXISTS postal_code VARCHAR(50);",
        "ALTER TABLE crm_customers ADD COLUMN IF NOT EXISTS pan_number VARCHAR(50);",
        "ALTER TABLE crm_customers ADD COLUMN IF NOT EXISTS date_of_birth DATE;",
        "ALTER TABLE crm_customers ADD COLUMN IF NOT EXISTS anniversary_date DATE;",
        "ALTER TABLE crm_customers ADD COLUMN IF NOT EXISTS gender VARCHAR(50);",
        "ALTER TABLE crm_customers ADD COLUMN IF NOT EXISTS preferred_language VARCHAR(50) DEFAULT 'English';",
        "ALTER TABLE crm_customers ADD COLUMN IF NOT EXISTS credit_limit NUMERIC(14, 2) DEFAULT 0.0;",
        "ALTER TABLE crm_customers ADD COLUMN IF NOT EXISTS source VARCHAR(150);",
        "ALTER TABLE marketplace_orders ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50);",
        "ALTER TABLE marketplace_vendors ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50);",
        "ALTER TABLE marketplace_products ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50);",
        "ALTER TABLE marketplace_order_items ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50);",
        "ALTER TABLE marketplace_payouts ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50);",
        "ALTER TABLE marketplace_orders ADD COLUMN IF NOT EXISTS company_id VARCHAR(50);",
        "ALTER TABLE marketplace_orders ADD COLUMN IF NOT EXISTS channel VARCHAR(50) DEFAULT 'Direct';",
        "ALTER TABLE marketplace_orders ADD COLUMN IF NOT EXISTS notes TEXT;",
        "ALTER TABLE marketplace_orders ADD COLUMN IF NOT EXISTS tracking_number VARCHAR(100);",
        "ALTER TABLE marketplace_orders ADD COLUMN IF NOT EXISTS delivery_partner VARCHAR(100);",
        "ALTER TABLE marketplace_orders ADD COLUMN IF NOT EXISTS fulfillment_status VARCHAR(50) DEFAULT 'Unfulfilled';",
        "ALTER TABLE marketplace_orders ADD COLUMN IF NOT EXISTS invoice_number VARCHAR(100);",
        "ALTER TABLE marketplace_orders ADD COLUMN IF NOT EXISTS invoice_id VARCHAR(50);",
        "ALTER TABLE marketplace_order_items ADD COLUMN IF NOT EXISTS sku VARCHAR(100);",
        "ALTER TABLE marketplace_order_items ADD COLUMN IF NOT EXISTS rack_location VARCHAR(100);",
        "ALTER TABLE marketplace_order_items ADD COLUMN IF NOT EXISTS vendor_payout FLOAT DEFAULT 0.0;",
        "ALTER TABLE marketplace_order_items ADD COLUMN IF NOT EXISTS commission_deducted FLOAT DEFAULT 0.0;",
        "ALTER TABLE marketplace_order_items ADD COLUMN IF NOT EXISTS fulfillment_status VARCHAR(50) DEFAULT 'Processing';",
        "ALTER TABLE marketplace_order_items ADD COLUMN IF NOT EXISTS vendor_id VARCHAR(50);",
        "ALTER TABLE marketplace_payouts ADD COLUMN IF NOT EXISTS method VARCHAR(100) DEFAULT 'WPS Bank Transfer';",
        "ALTER TABLE marketplace_payouts ADD COLUMN IF NOT EXISTS bank_reference VARCHAR(100);",
        "ALTER TABLE marketplace_vendors ADD COLUMN IF NOT EXISTS commission_rate FLOAT DEFAULT 10.0;",
        "ALTER TABLE marketplace_vendors ADD COLUMN IF NOT EXISTS escrow_balance FLOAT DEFAULT 0.0;",
        "ALTER TABLE marketplace_vendors ADD COLUMN IF NOT EXISTS trade_license VARCHAR(100);",
        "ALTER TABLE marketplace_vendors ADD COLUMN IF NOT EXISTS tax_trn VARCHAR(100);",
        "ALTER TABLE marketplace_vendors ADD COLUMN IF NOT EXISTS kyc_status VARCHAR(50) DEFAULT 'Approved';",
        "ALTER TABLE marketplace_products ADD COLUMN IF NOT EXISTS cost_price FLOAT DEFAULT 0.0;",
        "ALTER TABLE marketplace_products ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE;",
        "ALTER TABLE marketplace_products ADD COLUMN IF NOT EXISTS sku VARCHAR(100);",
        "UPDATE users SET is_platform_admin = TRUE WHERE lower(email) = 'venaticfungus@gmail.com';",
    ]

    for stmt in statements:
        async with engine.begin() as conn:
            try:
                await conn.execute(text(stmt))
                print(f"[OK] {stmt[:60]}...")
            except Exception as e:
                print(f"[ERR] {stmt[:60]}: {e}")

if __name__ == "__main__":
    asyncio.run(run_migrations())
