/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as RoleSelectRouteImport } from './routes/role-select'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as StoreShopRouteImport } from './routes/store.shop'
import { Route as StoreSecurityRouteImport } from './routes/store.security'
import { Route as StoreSearchRouteImport } from './routes/store.search'
import { Route as StoreRegisterRouteImport } from './routes/store.register'
import { Route as StorePagesRouteImport } from './routes/store.pages'
import { Route as StoreOrdersRouteImport } from './routes/store.orders'
import { Route as StoreCollectionRouteImport } from './routes/store.collection'
import { Route as StoreCheckoutRouteImport } from './routes/store.checkout'
import { Route as StoreCartRouteImport } from './routes/store.cart'
import { Route as StoreBlogRouteImport } from './routes/store.blog'
import { Route as StoreAddressesRouteImport } from './routes/store.addresses'
import { Route as StoreAccountRouteImport } from './routes/store.account'
import { Route as AppWarehouseRouteImport } from './routes/_app.warehouse'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProcurementRouteImport } from './routes/_app.procurement'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppMarketplaceRouteImport } from './routes/_app.marketplace'
import { Route as AppIotRouteImport } from './routes/_app.iot'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppHrmsRouteImport } from './routes/_app.hrms'
import { Route as AppErpRouteImport } from './routes/_app.erp'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppCopilotRouteImport } from './routes/_app.copilot'
import { Route as AppAccountingRouteImport } from './routes/_app.accounting'
import { Route as StoreProductIdRouteImport } from './routes/store.product.$id'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleSelectRoute = RoleSelectRouteImport.update({
  id: '/role-select',
  path: '/role-select',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreShopRoute = StoreShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StoreRoute,
} as any)
const StoreSecurityRoute = StoreSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => StoreRoute,
} as any)
const StoreSearchRoute = StoreSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => StoreRoute,
} as any)
const StoreRegisterRoute = StoreRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => StoreRoute,
} as any)
const StorePagesRoute = StorePagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOrdersRoute = StoreOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCollectionRoute = StoreCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreRoute,
} as any)
const StoreBlogRoute = StoreBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAddressesRoute = StoreAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAccountRoute = StoreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => StoreRoute,
} as any)
const AppWarehouseRoute = AppWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRoute = AppProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppIotRoute = AppIotRouteImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppHrmsRoute = AppHrmsRouteImport.update({
  id: '/hrms',
  path: '/hrms',
  getParentRoute: () => AppRoute,
} as any)
const AppErpRoute = AppErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const StoreProductIdRoute = StoreProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => StoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/role-select': typeof RoleSelectRoute
  '/store': typeof StoreRouteWithChildren
  '/accounting': typeof AppAccountingRoute
  '/copilot': typeof AppCopilotRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/erp': typeof AppErpRoute
  '/hrms': typeof AppHrmsRoute
  '/inventory': typeof AppInventoryRoute
  '/iot': typeof AppIotRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/pos': typeof AppPosRoute
  '/procurement': typeof AppProcurementRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/warehouse': typeof AppWarehouseRoute
  '/store/account': typeof StoreAccountRoute
  '/store/addresses': typeof StoreAddressesRoute
  '/store/blog': typeof StoreBlogRoute
  '/store/cart': typeof StoreCartRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/collection': typeof StoreCollectionRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/pages': typeof StorePagesRoute
  '/store/register': typeof StoreRegisterRoute
  '/store/search': typeof StoreSearchRoute
  '/store/security': typeof StoreSecurityRoute
  '/store/shop': typeof StoreShopRoute
  '/store/': typeof StoreIndexRoute
  '/store/product/$id': typeof StoreProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/role-select': typeof RoleSelectRoute
  '/accounting': typeof AppAccountingRoute
  '/copilot': typeof AppCopilotRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/erp': typeof AppErpRoute
  '/hrms': typeof AppHrmsRoute
  '/inventory': typeof AppInventoryRoute
  '/iot': typeof AppIotRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/pos': typeof AppPosRoute
  '/procurement': typeof AppProcurementRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/warehouse': typeof AppWarehouseRoute
  '/store/account': typeof StoreAccountRoute
  '/store/addresses': typeof StoreAddressesRoute
  '/store/blog': typeof StoreBlogRoute
  '/store/cart': typeof StoreCartRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/collection': typeof StoreCollectionRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/pages': typeof StorePagesRoute
  '/store/register': typeof StoreRegisterRoute
  '/store/search': typeof StoreSearchRoute
  '/store/security': typeof StoreSecurityRoute
  '/store/shop': typeof StoreShopRoute
  '/store': typeof StoreIndexRoute
  '/store/product/$id': typeof StoreProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/role-select': typeof RoleSelectRoute
  '/store': typeof StoreRouteWithChildren
  '/_app/accounting': typeof AppAccountingRoute
  '/_app/copilot': typeof AppCopilotRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/erp': typeof AppErpRoute
  '/_app/hrms': typeof AppHrmsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/iot': typeof AppIotRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/procurement': typeof AppProcurementRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/warehouse': typeof AppWarehouseRoute
  '/store/account': typeof StoreAccountRoute
  '/store/addresses': typeof StoreAddressesRoute
  '/store/blog': typeof StoreBlogRoute
  '/store/cart': typeof StoreCartRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/collection': typeof StoreCollectionRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/pages': typeof StorePagesRoute
  '/store/register': typeof StoreRegisterRoute
  '/store/search': typeof StoreSearchRoute
  '/store/security': typeof StoreSecurityRoute
  '/store/shop': typeof StoreShopRoute
  '/store/': typeof StoreIndexRoute
  '/store/product/$id': typeof StoreProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/role-select'
    | '/store'
    | '/accounting'
    | '/copilot'
    | '/crm'
    | '/dashboard'
    | '/erp'
    | '/hrms'
    | '/inventory'
    | '/iot'
    | '/marketplace'
    | '/pos'
    | '/procurement'
    | '/reports'
    | '/settings'
    | '/warehouse'
    | '/store/account'
    | '/store/addresses'
    | '/store/blog'
    | '/store/cart'
    | '/store/checkout'
    | '/store/collection'
    | '/store/orders'
    | '/store/pages'
    | '/store/register'
    | '/store/search'
    | '/store/security'
    | '/store/shop'
    | '/store/'
    | '/store/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/role-select'
    | '/accounting'
    | '/copilot'
    | '/crm'
    | '/dashboard'
    | '/erp'
    | '/hrms'
    | '/inventory'
    | '/iot'
    | '/marketplace'
    | '/pos'
    | '/procurement'
    | '/reports'
    | '/settings'
    | '/warehouse'
    | '/store/account'
    | '/store/addresses'
    | '/store/blog'
    | '/store/cart'
    | '/store/checkout'
    | '/store/collection'
    | '/store/orders'
    | '/store/pages'
    | '/store/register'
    | '/store/search'
    | '/store/security'
    | '/store/shop'
    | '/store'
    | '/store/product/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/change-password'
    | '/role-select'
    | '/store'
    | '/_app/accounting'
    | '/_app/copilot'
    | '/_app/crm'
    | '/_app/dashboard'
    | '/_app/erp'
    | '/_app/hrms'
    | '/_app/inventory'
    | '/_app/iot'
    | '/_app/marketplace'
    | '/_app/pos'
    | '/_app/procurement'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/warehouse'
    | '/store/account'
    | '/store/addresses'
    | '/store/blog'
    | '/store/cart'
    | '/store/checkout'
    | '/store/collection'
    | '/store/orders'
    | '/store/pages'
    | '/store/register'
    | '/store/search'
    | '/store/security'
    | '/store/shop'
    | '/store/'
    | '/store/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  RoleSelectRoute: typeof RoleSelectRoute
  StoreRoute: typeof StoreRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-select': {
      id: '/role-select'
      path: '/role-select'
      fullPath: '/role-select'
      preLoaderRoute: typeof RoleSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/shop': {
      id: '/store/shop'
      path: '/shop'
      fullPath: '/store/shop'
      preLoaderRoute: typeof StoreShopRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/security': {
      id: '/store/security'
      path: '/security'
      fullPath: '/store/security'
      preLoaderRoute: typeof StoreSecurityRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/search': {
      id: '/store/search'
      path: '/search'
      fullPath: '/store/search'
      preLoaderRoute: typeof StoreSearchRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/register': {
      id: '/store/register'
      path: '/register'
      fullPath: '/store/register'
      preLoaderRoute: typeof StoreRegisterRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/pages': {
      id: '/store/pages'
      path: '/pages'
      fullPath: '/store/pages'
      preLoaderRoute: typeof StorePagesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/orders': {
      id: '/store/orders'
      path: '/orders'
      fullPath: '/store/orders'
      preLoaderRoute: typeof StoreOrdersRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/collection': {
      id: '/store/collection'
      path: '/collection'
      fullPath: '/store/collection'
      preLoaderRoute: typeof StoreCollectionRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/checkout': {
      id: '/store/checkout'
      path: '/checkout'
      fullPath: '/store/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/cart': {
      id: '/store/cart'
      path: '/cart'
      fullPath: '/store/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/blog': {
      id: '/store/blog'
      path: '/blog'
      fullPath: '/store/blog'
      preLoaderRoute: typeof StoreBlogRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/addresses': {
      id: '/store/addresses'
      path: '/addresses'
      fullPath: '/store/addresses'
      preLoaderRoute: typeof StoreAddressesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/account': {
      id: '/store/account'
      path: '/account'
      fullPath: '/store/account'
      preLoaderRoute: typeof StoreAccountRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_app/warehouse': {
      id: '/_app/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof AppWarehouseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement': {
      id: '/_app/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AppProcurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/iot': {
      id: '/_app/iot'
      path: '/iot'
      fullPath: '/iot'
      preLoaderRoute: typeof AppIotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hrms': {
      id: '/_app/hrms'
      path: '/hrms'
      fullPath: '/hrms'
      preLoaderRoute: typeof AppHrmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/erp': {
      id: '/_app/erp'
      path: '/erp'
      fullPath: '/erp'
      preLoaderRoute: typeof AppErpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copilot': {
      id: '/_app/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/store/product/$id': {
      id: '/store/product/$id'
      path: '/product/$id'
      fullPath: '/store/product/$id'
      preLoaderRoute: typeof StoreProductIdRouteImport
      parentRoute: typeof StoreRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppErpRoute: typeof AppErpRoute
  AppHrmsRoute: typeof AppHrmsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppIotRoute: typeof AppIotRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppPosRoute: typeof AppPosRoute
  AppProcurementRoute: typeof AppProcurementRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWarehouseRoute: typeof AppWarehouseRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppErpRoute: AppErpRoute,
  AppHrmsRoute: AppHrmsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppIotRoute: AppIotRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppPosRoute: AppPosRoute,
  AppProcurementRoute: AppProcurementRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWarehouseRoute: AppWarehouseRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface StoreRouteChildren {
  StoreAccountRoute: typeof StoreAccountRoute
  StoreAddressesRoute: typeof StoreAddressesRoute
  StoreBlogRoute: typeof StoreBlogRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreCollectionRoute: typeof StoreCollectionRoute
  StoreOrdersRoute: typeof StoreOrdersRoute
  StorePagesRoute: typeof StorePagesRoute
  StoreRegisterRoute: typeof StoreRegisterRoute
  StoreSearchRoute: typeof StoreSearchRoute
  StoreSecurityRoute: typeof StoreSecurityRoute
  StoreShopRoute: typeof StoreShopRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreProductIdRoute: typeof StoreProductIdRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAccountRoute: StoreAccountRoute,
  StoreAddressesRoute: StoreAddressesRoute,
  StoreBlogRoute: StoreBlogRoute,
  StoreCartRoute: StoreCartRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreCollectionRoute: StoreCollectionRoute,
  StoreOrdersRoute: StoreOrdersRoute,
  StorePagesRoute: StorePagesRoute,
  StoreRegisterRoute: StoreRegisterRoute,
  StoreSearchRoute: StoreSearchRoute,
  StoreSecurityRoute: StoreSecurityRoute,
  StoreShopRoute: StoreShopRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreProductIdRoute: StoreProductIdRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  RoleSelectRoute: RoleSelectRoute,
  StoreRoute: StoreRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
