/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as RoleSelectRouteImport } from './routes/role-select'
import { Route as AppAccountingRouteImport } from './routes/_app.accounting'
import { Route as AppCopilotRouteImport } from './routes/_app.copilot'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppErpRouteImport } from './routes/_app.erp'
import { Route as AppHrmsRouteImport } from './routes/_app.hrms'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppIotRouteImport } from './routes/_app.iot'
import { Route as AppMarketplaceRouteImport } from './routes/_app.marketplace'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppProcurementRouteImport } from './routes/_app.procurement'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppWarehouseRouteImport } from './routes/_app.warehouse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleSelectRoute = RoleSelectRouteImport.update({
  id: '/role-select',
  path: '/role-select',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppErpRoute = AppErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => AppRoute,
} as any)
const AppHrmsRoute = AppHrmsRouteImport.update({
  id: '/hrms',
  path: '/hrms',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppIotRoute = AppIotRouteImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRoute = AppProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehouseRoute = AppWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/role-select': typeof RoleSelectRoute
  '/accounting': typeof AppAccountingRoute
  '/copilot': typeof AppCopilotRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/erp': typeof AppErpRoute
  '/hrms': typeof AppHrmsRoute
  '/inventory': typeof AppInventoryRoute
  '/iot': typeof AppIotRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/pos': typeof AppPosRoute
  '/procurement': typeof AppProcurementRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/warehouse': typeof AppWarehouseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/role-select': typeof RoleSelectRoute
  '/accounting': typeof AppAccountingRoute
  '/copilot': typeof AppCopilotRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/erp': typeof AppErpRoute
  '/hrms': typeof AppHrmsRoute
  '/inventory': typeof AppInventoryRoute
  '/iot': typeof AppIotRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/pos': typeof AppPosRoute
  '/procurement': typeof AppProcurementRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/warehouse': typeof AppWarehouseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/role-select': typeof RoleSelectRoute
  '/_app/accounting': typeof AppAccountingRoute
  '/_app/copilot': typeof AppCopilotRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/erp': typeof AppErpRoute
  '/_app/hrms': typeof AppHrmsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/iot': typeof AppIotRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/procurement': typeof AppProcurementRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/warehouse': typeof AppWarehouseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/role-select'
    | '/accounting'
    | '/copilot'
    | '/crm'
    | '/dashboard'
    | '/erp'
    | '/hrms'
    | '/inventory'
    | '/iot'
    | '/marketplace'
    | '/pos'
    | '/procurement'
    | '/reports'
    | '/settings'
    | '/warehouse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/role-select'
    | '/accounting'
    | '/copilot'
    | '/crm'
    | '/dashboard'
    | '/erp'
    | '/hrms'
    | '/inventory'
    | '/iot'
    | '/marketplace'
    | '/pos'
    | '/procurement'
    | '/reports'
    | '/settings'
    | '/warehouse'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/change-password'
    | '/role-select'
    | '/_app/accounting'
    | '/_app/copilot'
    | '/_app/crm'
    | '/_app/dashboard'
    | '/_app/erp'
    | '/_app/hrms'
    | '/_app/inventory'
    | '/_app/iot'
    | '/_app/marketplace'
    | '/_app/pos'
    | '/_app/procurement'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/warehouse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  RoleSelectRoute: typeof RoleSelectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-select': {
      id: '/role-select'
      path: '/role-select'
      fullPath: '/role-select'
      preLoaderRoute: typeof RoleSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copilot': {
      id: '/_app/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/erp': {
      id: '/_app/erp'
      path: '/erp'
      fullPath: '/erp'
      preLoaderRoute: typeof AppErpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hrms': {
      id: '/_app/hrms'
      path: '/hrms'
      fullPath: '/hrms'
      preLoaderRoute: typeof AppHrmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/iot': {
      id: '/_app/iot'
      path: '/iot'
      fullPath: '/iot'
      preLoaderRoute: typeof AppIotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement': {
      id: '/_app/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AppProcurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warehouse': {
      id: '/_app/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof AppWarehouseRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppErpRoute: typeof AppErpRoute
  AppHrmsRoute: typeof AppHrmsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppIotRoute: typeof AppIotRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppPosRoute: typeof AppPosRoute
  AppProcurementRoute: typeof AppProcurementRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWarehouseRoute: typeof AppWarehouseRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppErpRoute: AppErpRoute,
  AppHrmsRoute: AppHrmsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppIotRoute: AppIotRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppPosRoute: AppPosRoute,
  AppProcurementRoute: AppProcurementRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWarehouseRoute: AppWarehouseRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  RoleSelectRoute: RoleSelectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
