import React, { useState, useEffect, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Palette,
  Layout,
  FileText,
  Printer,
  Save,
  CheckCircle2,
  Sparkles,
  RotateCcw,
  Sliders,
  Shield,
  Eye,
  Plus,
  Trash2,
  Copy,
  Building,
  Check,
  Building2,
  DollarSign,
  Briefcase,
  ChevronRight,
  RefreshCw,
  Stamp,
  HelpCircle,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import {
  payrollApi,
  PayslipTemplate,
  Payslip,
} from "../../lib/api-client";
import { useCurrency } from "@/hooks/use-currency";
import { useTenant } from "@/contexts/tenant-context";
import { getActiveBillingGst } from "@/lib/receipt-template-store";

export const BUILTIN_PRESETS: Partial<PayslipTemplate>[] = [
  {
    name: "Modern Corporate",
    description: "Deep indigo & navy styling with high-contrast breakdown grid and dual verification blocks.",
    primary_color: "#1e1b4b",
    secondary_color: "#312e81",
    accent_color: "#15803d",
    background_color: "#ffffff",
    text_color: "#0f172a",
    font_family: "Inter, sans-serif",
    header_layout: "modern_split",
    paper_size: "A4",
    show_company_logo: true,
    show_company_address: true,
    show_bank_details: true,
    show_pan_aadhaar: true,
    show_leave_summary: false,
    show_signatures: true,
    show_watermark: true,
    watermark_text: "CONFIDENTIAL",
    footer_notes: "System Generated Electronic Salary Certificate • Valid without physical signature",
    left_signatory_title: "Employee Acknowledgment",
    right_signatory_title: "Authorized Finance Signatory",
  },
  {
    name: "Executive Sapphire",
    description: "Royal sapphire theme with highlighted earnings and elegant corporate banner.",
    primary_color: "#1e3a8a",
    secondary_color: "#2563eb",
    accent_color: "#059669",
    background_color: "#ffffff",
    text_color: "#1e293b",
    font_family: "Outfit, sans-serif",
    header_layout: "classic_banner",
    paper_size: "A4",
    show_company_logo: true,
    show_company_address: true,
    show_bank_details: true,
    show_pan_aadhaar: true,
    show_leave_summary: true,
    show_signatures: true,
    show_watermark: true,
    watermark_text: "ORIGINAL RECORD",
    footer_notes: "Confidential Enterprise Payroll Document • For Official Verification Only",
    left_signatory_title: "Staff Signature",
    right_signatory_title: "Head of Human Resources & Payroll",
  },
  {
    name: "Emerald Clean",
    description: "Eco emerald accents, clean white-space design, and modern pill indicators.",
    primary_color: "#064e3b",
    secondary_color: "#059669",
    accent_color: "#10b981",
    background_color: "#ffffff",
    text_color: "#111827",
    font_family: "Roboto, sans-serif",
    header_layout: "minimal_clean",
    paper_size: "A4",
    show_company_logo: true,
    show_company_address: true,
    show_bank_details: true,
    show_pan_aadhaar: false,
    show_leave_summary: false,
    show_signatures: true,
    show_watermark: false,
    watermark_text: "OFFICIAL",
    footer_notes: "Salary deposited via Electronic Direct Remittance. Contact HR for inquiries.",
    left_signatory_title: "Recipient Signature",
    right_signatory_title: "Authorized Controller",
  },
  {
    name: "Monochrome Minimal",
    description: "Classic black and dark slate legal styling optimized for sharp thermal/laser monochrome prints.",
    primary_color: "#0f172a",
    secondary_color: "#334155",
    accent_color: "#0f172a",
    background_color: "#ffffff",
    text_color: "#020617",
    font_family: "Inter, sans-serif",
    header_layout: "centered",
    paper_size: "A4",
    show_company_logo: false,
    show_company_address: true,
    show_bank_details: true,
    show_pan_aadhaar: true,
    show_leave_summary: false,
    show_signatures: true,
    show_watermark: true,
    watermark_text: "CONFIDENTIAL",
    footer_notes: "Official Statutory Record • Retention period: 5 years",
    left_signatory_title: "Employee Sign-off",
    right_signatory_title: "Finance & Accounts Authority",
  },
  {
    name: "Tech Violet",
    description: "Futuristic purple-indigo tones with pill badges and modern border curves.",
    primary_color: "#4c1d95",
    secondary_color: "#7c3aed",
    accent_color: "#10b981",
    background_color: "#ffffff",
    text_color: "#0f172a",
    font_family: "Outfit, sans-serif",
    header_layout: "modern_split",
    paper_size: "A4",
    show_company_logo: true,
    show_company_address: true,
    show_bank_details: true,
    show_pan_aadhaar: true,
    show_leave_summary: true,
    show_signatures: true,
    show_watermark: true,
    watermark_text: "PAYROLL CONFIRMED",
    footer_notes: "Generated by BusinessOS Autonomous HRMS Engine. Valid without physical signature.",
    left_signatory_title: "Employee Signature",
    right_signatory_title: "VP of People Operations",
  },
  {
    name: "Compact Legal Voucher",
    description: "High-density single-column voucher layout designed for paper savings and compact physical filing.",
    primary_color: "#374151",
    secondary_color: "#4b5563",
    accent_color: "#059669",
    background_color: "#ffffff",
    text_color: "#111827",
    font_family: "JetBrains Mono, monospace",
    header_layout: "minimal_clean",
    paper_size: "Compact",
    show_company_logo: false,
    show_company_address: true,
    show_bank_details: true,
    show_pan_aadhaar: false,
    show_leave_summary: false,
    show_signatures: true,
    show_watermark: false,
    watermark_text: "COPY",
    footer_notes: "Compact Pay Voucher. Retain for tax documentation.",
    left_signatory_title: "Acknowledged By",
    right_signatory_title: "Disbursing Officer",
  },
];

const COLOR_PALETTES = [
  { name: "Navy Corporate", primary: "#1e1b4b", secondary: "#312e81", accent: "#15803d" },
  { name: "Sapphire Blue", primary: "#1e3a8a", secondary: "#2563eb", accent: "#059669" },
  { name: "Emerald Forest", primary: "#064e3b", secondary: "#059669", accent: "#10b981" },
  { name: "Royal Purple", primary: "#4c1d95", secondary: "#7c3aed", accent: "#059669" },
  { name: "Crimson Maroon", primary: "#881337", secondary: "#be123c", accent: "#15803d" },
  { name: "Slate Monochrome", primary: "#0f172a", secondary: "#334155", accent: "#0f172a" },
  { name: "Warm Amber", primary: "#78350f", secondary: "#d97706", accent: "#15803d" },
];

const FONT_OPTIONS = [
  { label: "Inter (Modern Clean)", value: "Inter, sans-serif" },
  { label: "Outfit (Geometric)", value: "Outfit, sans-serif" },
  { label: "Roboto (Universal)", value: "Roboto, sans-serif" },
  { label: "Georgia (Serif Executive)", value: "Georgia, serif" },
  { label: "JetBrains Mono (Technical)", value: "JetBrains Mono, monospace" },
];

export function PayslipTemplateStudio() {
  const { currency } = useCurrency();
  const { tenant } = useTenant();
  const activeGst = getActiveBillingGst();

  const orgName = activeGst?.trade_name || activeGst?.legal_name || tenant?.name || "BusinessOS Enterprise";
  const orgLogo = (activeGst as any)?.logo_url || tenant?.logo_url || (tenant as any)?.raw?.logo_url || "";
  const orgInitials = orgName.substring(0, 2).toUpperCase();
  const orgAddress = activeGst?.address || tenant?.settings?.address || "100 Innovation Boulevard, Tech District, Suite 400";
  const orgGstin = activeGst?.gstin || tenant?.settings?.gstin || "07AAAAA0000A1Z5";
  const orgCin = activeGst?.cin || tenant?.settings?.cin || "U72200DL2024PTC123456";
  const orgEmail = activeGst?.email || tenant?.settings?.email || "hr@businessos.ai";
  const orgPhone = activeGst?.phone || tenant?.settings?.phone || "+91 (800) 555-0199";

  const [templates, setTemplates] = useState<PayslipTemplate[]>([]);
  const [selectedTemplate, setSelectedTemplate] = useState<Partial<PayslipTemplate>>(BUILTIN_PRESETS[0]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [activeTab, setActiveTab] = useState<"style" | "content" | "signatories">("style");
  const [recentSlips, setRecentSlips] = useState<Payslip[]>([]);
  const [previewSlipIndex, setPreviewSlipIndex] = useState<number>(-1); // -1 = mock data

  // Load templates and recent payslips
  const loadTemplatesData = async () => {
    setLoading(true);
    try {
      const [resTemplates, resSlips] = await Promise.all([
        payrollApi.listTemplates().catch(() => []),
        payrollApi.listPayslips().catch(() => []),
      ]);

      setRecentSlips(resSlips || []);

      if (resTemplates && resTemplates.length > 0) {
        setTemplates(resTemplates);
        const defaultOne = resTemplates.find(t => t.is_default) || resTemplates[0];
        setSelectedTemplate(defaultOne);
      } else {
        // First time initialization: pick builtin default
        setSelectedTemplate(BUILTIN_PRESETS[0]);
      }
    } catch (e) {
      console.error("Failed loading templates", e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadTemplatesData();
  }, []);

  // Mock payslip for preview
  const mockPayslip: Payslip = useMemo(() => {
    if (previewSlipIndex >= 0 && recentSlips[previewSlipIndex]) {
      return recentSlips[previewSlipIndex];
    }
    return {
      id: "demo-slip-98214-preview",
      tenant_id: tenant?.id || "demo-tenant",
      employee_id: "demo-emp-01",
      employee_name: "Dr. Alexander Vance",
      employee_code: "EMP-2026-0042",
      department: "Engineering & Architecture",
      designation: "Principal AI Infrastructure Architect",
      month: 7,
      year: 2026,
      basic_salary: 85000,
      hra: 34000,
      other_allowances: 21000,
      gross_salary: 140000,
      pf_deduction: 10200,
      esi_deduction: 0,
      tds_deduction: 14800,
      other_deductions: 2000,
      net_salary: 113000,
      status: "Paid",
      payment_date: "2026-07-31",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    } as Payslip;
  }, [previewSlipIndex, recentSlips, tenant?.id]);

  // Apply a preset
  const handleApplyPreset = (preset: Partial<PayslipTemplate>) => {
    setSelectedTemplate(prev => ({
      ...prev,
      ...preset,
      name: prev.id ? prev.name : preset.name, // keep existing name if editing existing
    }));
    toast.success(`Loaded preset: ${preset.name}`);
  };

  // Save changes to current template or create new
  const handleSaveTemplate = async (setAsDefault = false) => {
    setSaving(true);
    try {
      const payload: Partial<PayslipTemplate> = {
        name: selectedTemplate.name || "Custom Payslip Template",
        description: selectedTemplate.description || "Tailored company payslip layout",
        primary_color: selectedTemplate.primary_color || "#1e1b4b",
        secondary_color: selectedTemplate.secondary_color || "#312e81",
        accent_color: selectedTemplate.accent_color || "#15803d",
        background_color: selectedTemplate.background_color || "#ffffff",
        text_color: selectedTemplate.text_color || "#0f172a",
        font_family: selectedTemplate.font_family || "Inter, sans-serif",
        header_layout: selectedTemplate.header_layout || "modern_split",
        paper_size: selectedTemplate.paper_size || "A4",
        show_company_logo: selectedTemplate.show_company_logo ?? true,
        show_company_address: selectedTemplate.show_company_address ?? true,
        show_bank_details: selectedTemplate.show_bank_details ?? true,
        show_pan_aadhaar: selectedTemplate.show_pan_aadhaar ?? true,
        show_leave_summary: selectedTemplate.show_leave_summary ?? false,
        show_signatures: selectedTemplate.show_signatures ?? true,
        show_watermark: selectedTemplate.show_watermark ?? true,
        watermark_text: selectedTemplate.watermark_text || "CONFIDENTIAL",
        footer_notes: selectedTemplate.footer_notes || "System Generated Electronic Salary Certificate",
        left_signatory_title: selectedTemplate.left_signatory_title || "Employee Acknowledgment",
        right_signatory_title: selectedTemplate.right_signatory_title || "Authorized Finance Signatory",
        is_default: setAsDefault || selectedTemplate.is_default || false,
      };

      let saved: PayslipTemplate;
      if (selectedTemplate.id) {
        saved = await payrollApi.updateTemplate(selectedTemplate.id, payload);
        toast.success("Payslip template updated successfully!");
      } else {
        saved = await payrollApi.createTemplate(payload);
        toast.success("New payslip template created successfully!");
      }

      if (setAsDefault && saved.id) {
        await payrollApi.setDefaultTemplate(saved.id);
        toast.success(`"${saved.name}" is now set as the active organization template!`);
      }

      await loadTemplatesData();
      setSelectedTemplate(saved);
    } catch (err: any) {
      toast.error(err?.message || "Failed to save payslip template");
    } finally {
      setSaving(false);
    }
  };

  // Set selected template as default
  const handleSetDefault = async (tmpl: PayslipTemplate) => {
    try {
      await payrollApi.setDefaultTemplate(tmpl.id);
      toast.success(`"${tmpl.name}" is now the active default payslip template`);
      await loadTemplatesData();
    } catch (err: any) {
      toast.error(err?.message || "Failed to set default template");
    }
  };

  // Delete a template
  const handleDeleteTemplate = async (tmpl: PayslipTemplate) => {
    if (!confirm(`Are you sure you want to delete template "${tmpl.name}"?`)) return;
    try {
      await payrollApi.deleteTemplate(tmpl.id);
      toast.success("Template deleted successfully");
      await loadTemplatesData();
      setSelectedTemplate(BUILTIN_PRESETS[0]);
    } catch (err: any) {
      toast.error(err?.message || "Failed to delete template");
    }
  };

  // Duplicate a template
  const handleDuplicate = () => {
    setSelectedTemplate({
      ...selectedTemplate,
      id: undefined,
      name: `${selectedTemplate.name || "Template"} (Copy)`,
      is_default: false,
    });
    toast.info("Created a duplicate draft. Adjust settings and click 'Save New Template'.");
  };

  // Trigger test print
  const handleTestPrint = () => {
    const printWin = window.open("", "_blank", "width=900,height=1100");
    if (!printWin) {
      alert("Please allow popups to preview and print the Payslip.");
      return;
    }

    const t = selectedTemplate;
    const ps = mockPayslip;
    const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
    const monthStr = monthNames[ps.month - 1] || `Month ${ps.month}`;
    const totalDeductions = (ps.pf_deduction || 0) + (ps.esi_deduction || 0) + (ps.tds_deduction || 0) + (ps.other_deductions || 0);

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Official Payslip - ${ps.employee_name} (${monthStr} ${ps.year})</title>
          <style>
            @page {
              size: ${t.paper_size === "Compact" ? "A5 portrait" : "A4 portrait"};
              margin: 12mm 16mm;
            }
            * { box-sizing: border-box; margin: 0; padding: 0; font-family: ${t.font_family || "sans-serif"}; }
            body { background: #ffffff; color: ${t.text_color || "#0f172a"}; padding: 20px; font-size: 9.5pt; line-height: 1.5; }
            .container { max-width: 760px; margin: 0 auto; border: 1.5px solid #cbd5e1; padding: 26px; border-radius: 8px; position: relative; overflow: hidden; }
            .watermark { position: absolute; top: 45%; left: 10%; right: 10%; text-align: center; font-size: 58pt; font-weight: 900; color: #000; opacity: 0.035; transform: rotate(-25deg); pointer-events: none; z-index: 0; text-transform: uppercase; letter-spacing: 4px; }
            .header { border-bottom: 2.5px solid ${t.primary_color || "#1e1b4b"}; padding-bottom: 14px; margin-bottom: 18px; display: flex; justify-content: space-between; align-items: flex-start; }
            .header h1 { font-size: 16pt; font-weight: 900; color: ${t.primary_color || "#1e1b4b"}; letter-spacing: -0.5px; }
            .header p { font-size: 8pt; color: #64748b; margin-top: 1px; }
            .title-banner { text-align: center; font-size: 11.5pt; font-weight: 800; color: ${t.primary_color || "#1e1b4b"}; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 16px; background: #f8fafc; border: 1px solid #e2e8f0; padding: 6px 0; border-radius: 6px; }
            .emp-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 12px; margin-bottom: 18px; font-size: 8.5pt; }
            .emp-row { display: flex; justify-content: space-between; padding: 2px 0; }
            .emp-label { color: #64748b; font-weight: 600; }
            .emp-val { color: #0f172a; font-weight: 700; }
            .table-wrap { width: 100%; border-collapse: collapse; margin-bottom: 18px; font-size: 9pt; }
            .table-wrap th { background: ${t.primary_color || "#1e1b4b"}; color: #ffffff; text-align: left; padding: 8px 10px; font-size: 8pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; }
            .table-wrap td { padding: 8px 10px; border-bottom: 1px solid #e2e8f0; }
            .col-earn { width: 50%; border-right: 1.5px solid #cbd5e1; vertical-align: top; }
            .col-ded { width: 50%; vertical-align: top; }
            .inner-row { display: flex; justify-content: space-between; padding: 4px 0; }
            .subtotal { border-top: 1.5px solid #cbd5e1; font-weight: 800; padding-top: 6px; margin-top: 6px; }
            .net-box { background: #f0fdf4; border: 1.5px solid #86efac; border-radius: 8px; padding: 14px 18px; display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; }
            .net-val { font-size: 16pt; font-weight: 900; color: ${t.accent_color || "#15803d"}; }
            .signatures { display: flex; justify-content: space-between; align-items: flex-end; margin-top: 36px; padding-top: 14px; border-top: 1px dashed #cbd5e1; }
            .sign-col { width: 45%; }
            .sign-line { height: 38px; border-bottom: 1.5px solid #0f172a; margin-bottom: 6px; }
            .footer { margin-top: 24px; padding-top: 8px; border-top: 1px solid #e2e8f0; display: flex; justify-content: space-between; font-size: 7.5pt; color: #94a3b8; }
            @media print { body { padding: 0; } .container { border: none; padding: 0; } }
          </style>
        </head>
        <body>
          <div class="container">
            ${t.show_watermark ? `<div class="watermark">${t.watermark_text || "CONFIDENTIAL"}</div>` : ""}
            <div class="header">
              <div style="display: flex; align-items: center; gap: 14px;">
                ${t.show_company_logo && orgLogo ? `<img src="${orgLogo}" alt="${orgName}" style="max-height: 48px; max-width: 140px; object-fit: contain;" />` : `<div style="width: 42px; height: 42px; border-radius: 8px; background: ${t.primary_color || "#1e1b4b"}; color: white; display: flex; align-items: center; justify-content: center; font-weight: 900; font-size: 13pt;">${orgInitials}</div>`}
                <div>
                  <h1>${orgName}</h1>
                  ${t.show_company_address ? `<p>${orgAddress}</p>` : ""}
                  <p>Email: ${orgEmail} • Phone: ${orgPhone}${orgGstin ? ` • GSTIN: ${orgGstin}` : ""}</p>
                </div>
              </div>
              <div style="text-align: right;">
                <span style="display:inline-block; background:${t.primary_color || "#1e1b4b"}; color:#fff; font-size:7.5pt; font-weight:800; padding:3px 8px; border-radius:4px; text-transform:uppercase;">Official Payslip</span>
                <p style="font-size:7.5pt; color:#64748b; margin-top:4px;">Period: ${monthStr} ${ps.year}</p>
                <p style="font-size:7.5pt; font-family:monospace; color:#64748b;">REF: PAY-${ps.year}-${ps.month.toString().padStart(2, '0')}-${ps.id.substring(0, 6).toUpperCase()}</p>
              </div>
            </div>

            <div class="title-banner">Salary Slip for ${monthStr} ${ps.year}</div>

            <div class="emp-grid">
              <div>
                <div class="emp-row"><span class="emp-label">Employee Name:</span><span class="emp-val">${ps.employee_name}</span></div>
                <div class="emp-row"><span class="emp-label">Employee Code:</span><span class="emp-val font-mono">${ps.employee_code}</span></div>
                <div class="emp-row"><span class="emp-label">Department:</span><span class="emp-val">${ps.department || "Enterprise Staff"}</span></div>
              </div>
              <div>
                <div class="emp-row"><span class="emp-label">Designation:</span><span class="emp-val">${ps.designation || "Staff Specialist"}</span></div>
                <div class="emp-row"><span class="emp-label">Payment Status:</span><span class="emp-val" style="color:${t.accent_color || "#16a34a"};">${ps.status}</span></div>
                ${t.show_bank_details ? `<div class="emp-row"><span class="emp-label">Payout Mode:</span><span class="emp-val">Direct Bank Remittance</span></div>` : ""}
              </div>
            </div>

            <table class="table-wrap">
              <thead>
                <tr>
                  <th style="width: 50%; border-right: 1.5px solid #ffffff;">Earnings (A)</th>
                  <th style="width: 50%;">Deductions (B)</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="col-earn">
                    <div class="inner-row"><span>Basic Salary</span><span>${currency.symbol}${ps.basic_salary.toLocaleString()}</span></div>
                    <div class="inner-row"><span>House Rent Allowance (HRA)</span><span>${currency.symbol}${ps.hra.toLocaleString()}</span></div>
                    <div class="inner-row"><span>Special & Other Allowances</span><span>${currency.symbol}${ps.other_allowances.toLocaleString()}</span></div>
                    <div class="inner-row subtotal"><span>Gross Earnings (A)</span><span>${currency.symbol}${ps.gross_salary.toLocaleString()}</span></div>
                  </td>
                  <td class="col-ded">
                    <div class="inner-row"><span>Provident Fund (PF)</span><span>${currency.symbol}${ps.pf_deduction.toLocaleString()}</span></div>
                    <div class="inner-row"><span>ESI Contribution</span><span>${currency.symbol}${ps.esi_deduction.toLocaleString()}</span></div>
                    <div class="inner-row"><span>TDS / Income Tax</span><span>${currency.symbol}${ps.tds_deduction.toLocaleString()}</span></div>
                    <div class="inner-row"><span>Other Deductions</span><span>${currency.symbol}${ps.other_deductions.toLocaleString()}</span></div>
                    <div class="inner-row subtotal"><span>Total Deductions (B)</span><span>${currency.symbol}${totalDeductions.toLocaleString()}</span></div>
                  </td>
                </tr>
              </tbody>
            </table>

            <div class="net-box">
              <div>
                <p style="font-size:9pt; font-weight:700; color:${t.accent_color || "#15803d"}; text-transform:uppercase;">Net Salary Disbursed (A - B)</p>
                <p style="font-size:8pt; color:#15803d; font-style:italic; margin-top:2px;">Disbursed via automated corporate payroll transfer</p>
              </div>
              <div class="net-val">${currency.symbol}${ps.net_salary.toLocaleString()}</div>
            </div>

            ${t.show_signatures ? `
              <div class="signatures">
                <div class="sign-col">
                  <div class="sign-line"></div>
                  <div style="font-size: 9pt; font-weight: 800;">${t.left_signatory_title || "Employee Acknowledgment"}</div>
                  <div style="font-size: 7.5pt; color: #64748b;">${ps.employee_name}</div>
                </div>
                <div class="sign-col" style="text-align: right;">
                  <div class="sign-line"></div>
                  <div style="font-size: 9pt; font-weight: 800;">${t.right_signatory_title || "Authorized Finance Signatory"}</div>
                  <div style="font-size: 7.5pt; color: #64748b;">Payroll Operations • ${orgName}</div>
                </div>
              </div>
            ` : ""}

            <div class="footer">
              <div>${t.footer_notes || "System Generated Electronic Salary Certificate"}</div>
              <div>${orgName} • Confidential</div>
            </div>
          </div>

          <script>
            window.onload = function() {
              setTimeout(function() {
                window.print();
              }, 300);
            };
          </script>
        </body>
      </html>
    `;

    printWin.document.open();
    printWin.document.write(html);
    printWin.document.close();
  };

  return (
    <div className="space-y-6">
      {/* ─── Top Page Header ─── */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-card border border-border/60 p-6 rounded-2xl shadow-sm">
        <div>
          <div className="flex items-center gap-2.5">
            <div className="p-2.5 rounded-xl bg-primary/10 text-primary">
              <Palette className="size-6" />
            </div>
            <div>
              <h2 className="text-2xl font-black tracking-tight text-foreground flex items-center gap-2">
                Payslip Template Studio
                <span className="text-xs font-semibold px-2.5 py-0.5 rounded-full bg-emerald-500/10 text-emerald-600 border border-emerald-500/20">
                  Live Customizer
                </span>
              </h2>
              <p className="text-xs text-muted-foreground mt-0.5">
                Design, brand, and configure corporate salary slips with live real-time preview & print compliance.
              </p>
            </div>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={handleTestPrint}
            className="h-10 font-bold gap-2 text-foreground hover:bg-muted"
          >
            <Printer className="size-4 text-primary" /> Test Print / PDF
          </Button>

          <Button
            variant="outline"
            size="sm"
            onClick={handleDuplicate}
            className="h-10 font-bold gap-1.5"
            title="Duplicate as new template draft"
          >
            <Copy className="size-4" /> Duplicate
          </Button>

          <Button
            variant="default"
            size="sm"
            onClick={() => handleSaveTemplate(false)}
            disabled={saving}
            className="h-10 font-bold gap-2 gradient-brand text-white shadow-md hover:opacity-95"
          >
            <Save className="size-4" /> {saving ? "Saving..." : "Save Template"}
          </Button>

          <Button
            variant="default"
            size="sm"
            onClick={() => handleSaveTemplate(true)}
            disabled={saving}
            className="h-10 font-bold gap-2 bg-emerald-600 hover:bg-emerald-700 text-white shadow-md"
          >
            <CheckCircle2 className="size-4" /> Save & Set as Default
          </Button>
        </div>
      </div>

      {/* ─── Presets Gallery Carousel / Grid ─── */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="size-4 text-primary" />
            <h3 className="text-sm font-bold uppercase tracking-wider text-muted-foreground">
              Ready-to-use Corporate Design Presets
            </h3>
          </div>
          {templates.length > 0 && (
            <span className="text-xs text-muted-foreground font-medium">
              {templates.length} saved custom {templates.length === 1 ? "template" : "templates"}
            </span>
          )}
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
          {BUILTIN_PRESETS.map((preset, idx) => {
            const isSelected = selectedTemplate.name === preset.name;
            return (
              <button
                key={idx}
                type="button"
                onClick={() => handleApplyPreset(preset)}
                className={`text-left p-3.5 rounded-xl border transition-all relative overflow-hidden group ${
                  isSelected
                    ? "border-primary bg-primary/5 ring-2 ring-primary/20 shadow-md"
                    : "border-border/60 hover:border-border hover:bg-muted/40 bg-card"
                }`}
              >
                <div
                  className="h-2 rounded-full mb-2.5 transition-transform group-hover:scale-105"
                  style={{ background: preset.primary_color }}
                />
                <div className="font-bold text-xs text-foreground truncate">{preset.name}</div>
                <div className="text-[10px] text-muted-foreground mt-0.5 line-clamp-2 leading-relaxed">
                  {preset.description}
                </div>
                {isSelected && (
                  <div className="absolute top-2 right-2 text-primary">
                    <Check className="size-3.5" />
                  </div>
                )}
              </button>
            );
          })}
        </div>
      </div>

      {/* ─── Main Two-Column Layout: Controls & Live Preview ─── */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* ── Left Column: Configuration Controls (5 cols) ── */}
        <div className="lg:col-span-5 space-y-4">
          <div className="bg-card border border-border/70 rounded-2xl p-5 shadow-sm space-y-5">
            {/* Template Identity Info */}
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
                  Template Identity
                </label>
                {selectedTemplate.is_default && (
                  <span className="text-[10px] font-bold bg-emerald-500/10 text-emerald-600 border border-emerald-500/20 px-2 py-0.5 rounded-full flex items-center gap-1">
                    <CheckCircle2 className="size-3" /> Active Organization Default
                  </span>
                )}
              </div>
              <div className="space-y-2">
                <input
                  type="text"
                  value={selectedTemplate.name || ""}
                  onChange={e => setSelectedTemplate(prev => ({ ...prev, name: e.target.value }))}
                  placeholder="Template Name (e.g. Enterprise Global 2026)"
                  className="w-full h-10 px-3 text-sm font-semibold rounded-lg border bg-background text-foreground"
                />
                <input
                  type="text"
                  value={selectedTemplate.description || ""}
                  onChange={e => setSelectedTemplate(prev => ({ ...prev, description: e.target.value }))}
                  placeholder="Description / Purpose..."
                  className="w-full h-8 px-3 text-xs rounded-lg border bg-background text-muted-foreground"
                />
              </div>
            </div>

            {/* Sub-Tabs: Style vs Content vs Signatures */}
            <div className="flex border-b border-border/70 gap-1 pb-1">
              <button
                type="button"
                onClick={() => setActiveTab("style")}
                className={`px-3 py-2 text-xs font-bold rounded-lg transition-colors flex items-center gap-1.5 ${
                  activeTab === "style"
                    ? "bg-primary text-primary-foreground shadow-sm"
                    : "text-muted-foreground hover:bg-muted"
                }`}
              >
                <Palette className="size-3.5" /> Styling & Palette
              </button>
              <button
                type="button"
                onClick={() => setActiveTab("content")}
                className={`px-3 py-2 text-xs font-bold rounded-lg transition-colors flex items-center gap-1.5 ${
                  activeTab === "content"
                    ? "bg-primary text-primary-foreground shadow-sm"
                    : "text-muted-foreground hover:bg-muted"
                }`}
              >
                <Layout className="size-3.5" /> Sections & Branding
              </button>
              <button
                type="button"
                onClick={() => setActiveTab("signatories")}
                className={`px-3 py-2 text-xs font-bold rounded-lg transition-colors flex items-center gap-1.5 ${
                  activeTab === "signatories"
                    ? "bg-primary text-primary-foreground shadow-sm"
                    : "text-muted-foreground hover:bg-muted"
                }`}
              >
                <Stamp className="size-3.5" /> Signatures & Notes
              </button>
            </div>

            {/* Tab 1: Styling & Palette */}
            {activeTab === "style" && (
              <div className="space-y-4 pt-1">
                {/* Color Palette Presets */}
                <div className="space-y-2">
                  <label className="text-xs font-bold text-muted-foreground">Color Palette Presets</label>
                  <div className="grid grid-cols-4 gap-2">
                    {COLOR_PALETTES.map((pal, i) => (
                      <button
                        key={i}
                        type="button"
                        onClick={() =>
                          setSelectedTemplate(prev => ({
                            ...prev,
                            primary_color: pal.primary,
                            secondary_color: pal.secondary,
                            accent_color: pal.accent,
                          }))
                        }
                        className="p-2 rounded-lg border border-border/50 text-left hover:border-primary transition-all flex flex-col gap-1.5"
                      >
                        <div className="flex gap-1 h-3 rounded overflow-hidden">
                          <div className="flex-1" style={{ background: pal.primary }} />
                          <div className="flex-1" style={{ background: pal.secondary }} />
                          <div className="flex-1" style={{ background: pal.accent }} />
                        </div>
                        <span className="text-[10px] font-semibold text-foreground truncate">{pal.name}</span>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Custom Color Pickers */}
                <div className="grid grid-cols-3 gap-3">
                  <div className="space-y-1">
                    <label className="text-[11px] font-bold text-muted-foreground">Primary Banner</label>
                    <div className="flex items-center gap-2 border rounded-lg p-1.5 bg-background">
                      <input
                        type="color"
                        value={selectedTemplate.primary_color || "#1e1b4b"}
                        onChange={e => setSelectedTemplate(prev => ({ ...prev, primary_color: e.target.value }))}
                        className="w-6 h-6 rounded cursor-pointer border-0 p-0"
                      />
                      <span className="text-xs font-mono font-medium text-foreground uppercase">
                        {selectedTemplate.primary_color}
                      </span>
                    </div>
                  </div>

                  <div className="space-y-1">
                    <label className="text-[11px] font-bold text-muted-foreground">Secondary Tone</label>
                    <div className="flex items-center gap-2 border rounded-lg p-1.5 bg-background">
                      <input
                        type="color"
                        value={selectedTemplate.secondary_color || "#312e81"}
                        onChange={e => setSelectedTemplate(prev => ({ ...prev, secondary_color: e.target.value }))}
                        className="w-6 h-6 rounded cursor-pointer border-0 p-0"
                      />
                      <span className="text-xs font-mono font-medium text-foreground uppercase">
                        {selectedTemplate.secondary_color}
                      </span>
                    </div>
                  </div>

                  <div className="space-y-1">
                    <label className="text-[11px] font-bold text-muted-foreground">Net Pay Accent</label>
                    <div className="flex items-center gap-2 border rounded-lg p-1.5 bg-background">
                      <input
                        type="color"
                        value={selectedTemplate.accent_color || "#15803d"}
                        onChange={e => setSelectedTemplate(prev => ({ ...prev, accent_color: e.target.value }))}
                        className="w-6 h-6 rounded cursor-pointer border-0 p-0"
                      />
                      <span className="text-xs font-mono font-medium text-foreground uppercase">
                        {selectedTemplate.accent_color}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Typography & Layout */}
                <div className="grid grid-cols-2 gap-3">
                  <div className="space-y-1">
                    <label className="text-[11px] font-bold text-muted-foreground">Typography Font</label>
                    <select
                      value={selectedTemplate.font_family || "Inter, sans-serif"}
                      onChange={e => setSelectedTemplate(prev => ({ ...prev, font_family: e.target.value }))}
                      className="w-full h-9 px-2 text-xs rounded-lg border bg-background text-foreground"
                    >
                      {FONT_OPTIONS.map(f => (
                        <option key={f.value} value={f.value}>{f.label}</option>
                      ))}
                    </select>
                  </div>

                  <div className="space-y-1">
                    <label className="text-[11px] font-bold text-muted-foreground">Header Style</label>
                    <select
                      value={selectedTemplate.header_layout || "modern_split"}
                      onChange={e => setSelectedTemplate(prev => ({ ...prev, header_layout: e.target.value }))}
                      className="w-full h-9 px-2 text-xs rounded-lg border bg-background text-foreground"
                    >
                      <option value="modern_split">Modern Split (Logo Left)</option>
                      <option value="classic_banner">Classic Corporate Banner</option>
                      <option value="centered">Centered Formal Header</option>
                      <option value="minimal_clean">Minimal Clean Header</option>
                    </select>
                  </div>
                </div>

                {/* Paper Size */}
                <div className="space-y-1">
                  <label className="text-[11px] font-bold text-muted-foreground">Paper / Export Format</label>
                  <div className="grid grid-cols-3 gap-2">
                    {["A4", "Letter", "Compact"].map(p => (
                      <button
                        key={p}
                        type="button"
                        onClick={() => setSelectedTemplate(prev => ({ ...prev, paper_size: p }))}
                        className={`h-8 rounded-lg text-xs font-bold border transition-all ${
                          selectedTemplate.paper_size === p
                            ? "bg-primary text-primary-foreground border-primary"
                            : "bg-background text-muted-foreground border-border hover:bg-muted"
                        }`}
                      >
                        {p === "Compact" ? "Compact Slip" : `${p} Portrait`}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* Tab 2: Sections & Content Visibility */}
            {activeTab === "content" && (
              <div className="space-y-3 pt-1">
                <label className="text-xs font-bold text-muted-foreground">Visible Blocks & Branding</label>
                
                <div className="space-y-2">
                  <label className="flex items-center justify-between p-2.5 rounded-lg border bg-background hover:bg-muted/40 cursor-pointer">
                    <span className="text-xs font-semibold text-foreground">Company Logo & Branding</span>
                    <input
                      type="checkbox"
                      checked={selectedTemplate.show_company_logo ?? true}
                      onChange={e => setSelectedTemplate(prev => ({ ...prev, show_company_logo: e.target.checked }))}
                      className="w-4 h-4 rounded text-primary"
                    />
                  </label>

                  <label className="flex items-center justify-between p-2.5 rounded-lg border bg-background hover:bg-muted/40 cursor-pointer">
                    <span className="text-xs font-semibold text-foreground">Company Registered Address & Tax IDs</span>
                    <input
                      type="checkbox"
                      checked={selectedTemplate.show_company_address ?? true}
                      onChange={e => setSelectedTemplate(prev => ({ ...prev, show_company_address: e.target.checked }))}
                      className="w-4 h-4 rounded text-primary"
                    />
                  </label>

                  <label className="flex items-center justify-between p-2.5 rounded-lg border bg-background hover:bg-muted/40 cursor-pointer">
                    <span className="text-xs font-semibold text-foreground">Bank & Disbursal Mode Details</span>
                    <input
                      type="checkbox"
                      checked={selectedTemplate.show_bank_details ?? true}
                      onChange={e => setSelectedTemplate(prev => ({ ...prev, show_bank_details: e.target.checked }))}
                      className="w-4 h-4 rounded text-primary"
                    />
                  </label>

                  <label className="flex items-center justify-between p-2.5 rounded-lg border bg-background hover:bg-muted/40 cursor-pointer">
                    <span className="text-xs font-semibold text-foreground">Employee Statutory IDs (PAN / UAN)</span>
                    <input
                      type="checkbox"
                      checked={selectedTemplate.show_pan_aadhaar ?? true}
                      onChange={e => setSelectedTemplate(prev => ({ ...prev, show_pan_aadhaar: e.target.checked }))}
                      className="w-4 h-4 rounded text-primary"
                    />
                  </label>

                  <label className="flex items-center justify-between p-2.5 rounded-lg border bg-background hover:bg-muted/40 cursor-pointer">
                    <span className="text-xs font-semibold text-foreground">Security Watermark Overlay</span>
                    <input
                      type="checkbox"
                      checked={selectedTemplate.show_watermark ?? true}
                      onChange={e => setSelectedTemplate(prev => ({ ...prev, show_watermark: e.target.checked }))}
                      className="w-4 h-4 rounded text-primary"
                    />
                  </label>
                </div>

                {selectedTemplate.show_watermark && (
                  <div className="space-y-1 pt-1">
                    <label className="text-[11px] font-bold text-muted-foreground">Watermark Text</label>
                    <input
                      type="text"
                      value={selectedTemplate.watermark_text || "CONFIDENTIAL"}
                      onChange={e => setSelectedTemplate(prev => ({ ...prev, watermark_text: e.target.value }))}
                      placeholder="e.g. CONFIDENTIAL / ORIGINAL / OFFICIAL"
                      className="w-full h-8 px-3 text-xs font-bold uppercase rounded-lg border bg-background text-foreground"
                    />
                  </div>
                )}
              </div>
            )}

            {/* Tab 3: Signatures & Notes */}
            {activeTab === "signatories" && (
              <div className="space-y-4 pt-1">
                <label className="flex items-center justify-between p-2.5 rounded-lg border bg-background hover:bg-muted/40 cursor-pointer">
                  <span className="text-xs font-semibold text-foreground">Include Authorized Signatory Lines</span>
                  <input
                    type="checkbox"
                    checked={selectedTemplate.show_signatures ?? true}
                    onChange={e => setSelectedTemplate(prev => ({ ...prev, show_signatures: e.target.checked }))}
                    className="w-4 h-4 rounded text-primary"
                  />
                </label>

                {selectedTemplate.show_signatures && (
                  <div className="grid grid-cols-2 gap-3">
                    <div className="space-y-1">
                      <label className="text-[11px] font-bold text-muted-foreground">Left Signatory Block</label>
                      <input
                        type="text"
                        value={selectedTemplate.left_signatory_title || ""}
                        onChange={e => setSelectedTemplate(prev => ({ ...prev, left_signatory_title: e.target.value }))}
                        placeholder="Employee Acknowledgment"
                        className="w-full h-9 px-3 text-xs rounded-lg border bg-background text-foreground font-medium"
                      />
                    </div>
                    <div className="space-y-1">
                      <label className="text-[11px] font-bold text-muted-foreground">Right Signatory Block</label>
                      <input
                        type="text"
                        value={selectedTemplate.right_signatory_title || ""}
                        onChange={e => setSelectedTemplate(prev => ({ ...prev, right_signatory_title: e.target.value }))}
                        placeholder="Authorized Signatory"
                        className="w-full h-9 px-3 text-xs rounded-lg border bg-background text-foreground font-medium"
                      />
                    </div>
                  </div>
                )}

                <div className="space-y-1">
                  <label className="text-[11px] font-bold text-muted-foreground">Compliance / Footer Disclaimer</label>
                  <textarea
                    rows={2}
                    value={selectedTemplate.footer_notes || ""}
                    onChange={e => setSelectedTemplate(prev => ({ ...prev, footer_notes: e.target.value }))}
                    placeholder="System Generated Electronic Salary Certificate • Valid without physical signature"
                    className="w-full p-2.5 text-xs rounded-lg border bg-background text-foreground resize-none"
                  />
                </div>
              </div>
            )}
          </div>

          {/* Saved Templates List in Database */}
          {templates.length > 0 && (
            <div className="bg-card border border-border/70 rounded-2xl p-4 shadow-sm space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
                  Saved Organization Templates
                </span>
                <span className="text-xs text-muted-foreground">{templates.length} Total</span>
              </div>
              <div className="space-y-2 max-h-48 overflow-y-auto pr-1">
                {templates.map(t => (
                  <div
                    key={t.id}
                    className={`flex items-center justify-between p-2.5 rounded-xl border text-xs transition-all ${
                      selectedTemplate.id === t.id
                        ? "border-primary bg-primary/5 font-bold"
                        : "border-border/60 hover:bg-muted/40"
                    }`}
                  >
                    <button
                      type="button"
                      onClick={() => setSelectedTemplate(t)}
                      className="text-left flex-1 truncate flex items-center gap-2"
                    >
                      <span
                        className="w-2.5 h-2.5 rounded-full shrink-0"
                        style={{ background: t.primary_color }}
                      />
                      <span className="text-foreground truncate">{t.name}</span>
                      {t.is_default && (
                        <span className="text-[9px] font-bold bg-emerald-500/10 text-emerald-600 px-1.5 py-0.5 rounded">
                          DEFAULT
                        </span>
                      )}
                    </button>

                    <div className="flex items-center gap-1 shrink-0 ml-2">
                      {!t.is_default && (
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleSetDefault(t)}
                          className="h-7 px-2 text-[10px] font-bold text-emerald-600 hover:text-emerald-700"
                          title="Set as Default"
                        >
                          Make Default
                        </Button>
                      )}
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleDeleteTemplate(t)}
                        className="h-7 w-7 p-0 text-destructive hover:bg-destructive/10"
                        title="Delete template"
                      >
                        <Trash2 className="size-3.5" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* ── Right Column: Interactive Real-Time Live Preview (7 cols) ── */}
        <div className="lg:col-span-7 space-y-4">
          <div className="flex flex-wrap items-center justify-between gap-3 bg-card border border-border/70 p-3 rounded-2xl shadow-sm">
            <div className="flex items-center gap-2">
              <Eye className="size-4 text-primary" />
              <span className="text-xs font-bold text-foreground">Live Document Preview</span>
              <span className="text-[10px] px-2 py-0.5 rounded-full bg-muted font-mono text-muted-foreground">
                {selectedTemplate.paper_size || "A4"}
              </span>
            </div>

            {/* Switch preview data source */}
            <div className="flex items-center gap-2">
              <span className="text-[11px] text-muted-foreground font-medium">Data:</span>
              <select
                value={previewSlipIndex}
                onChange={e => setPreviewSlipIndex(parseInt(e.target.value))}
                className="h-7 px-2 text-xs rounded-md border bg-background text-foreground"
              >
                <option value="-1">Demo Employee (Dr. Alexander Vance)</option>
                {recentSlips.slice(0, 10).map((ps, idx) => (
                  <option key={ps.id} value={idx}>
                    {ps.employee_name} ({ps.month}/{ps.year})
                  </option>
                ))}
              </select>
            </div>
          </div>

          {/* Rendered Live Payslip Canvas */}
          <div className="bg-slate-100 dark:bg-slate-900/60 p-4 sm:p-6 rounded-2xl border border-border/70 shadow-inner flex justify-center overflow-x-auto">
            <div
              id="live-payslip-canvas"
              style={{
                fontFamily: selectedTemplate.font_family || "Inter, sans-serif",
                color: selectedTemplate.text_color || "#0f172a",
                backgroundColor: selectedTemplate.background_color || "#ffffff",
                maxWidth: selectedTemplate.paper_size === "Compact" ? "560px" : "720px",
                width: "100%",
              }}
              className="rounded-xl shadow-xl border border-slate-300 dark:border-slate-700 p-6 sm:p-8 relative overflow-hidden text-[12px] leading-relaxed select-none transition-all"
            >
              {/* Watermark */}
              {selectedTemplate.show_watermark && (
                <div className="absolute inset-0 flex items-center justify-center pointer-events-none select-none opacity-[0.035] rotate-[-25deg] text-6xl sm:text-7xl font-black text-slate-900 uppercase tracking-widest z-0">
                  {selectedTemplate.watermark_text || "CONFIDENTIAL"}
                </div>
              )}

              {/* ─── Header ─── */}
              <div
                style={{ borderBottomColor: selectedTemplate.primary_color || "#1e1b4b" }}
                className="border-b-2 pb-4 mb-4 flex justify-between items-start gap-4 relative z-10"
              >
                <div className="flex items-center gap-3">
                  {selectedTemplate.show_company_logo && orgLogo ? (
                    <img src={orgLogo} alt={orgName} className="h-10 w-auto object-contain" />
                  ) : (
                    <div
                      style={{ background: selectedTemplate.primary_color || "#1e1b4b" }}
                      className="size-10 rounded-xl text-white flex items-center justify-center font-black text-base shadow-sm shrink-0"
                    >
                      {orgInitials}
                    </div>
                  )}
                  <div>
                    <h1
                      style={{ color: selectedTemplate.primary_color || "#1e1b4b" }}
                      className="text-lg font-black tracking-tight leading-none"
                    >
                      {orgName}
                    </h1>
                    {selectedTemplate.show_company_address && (
                      <p className="text-[10px] text-slate-500 mt-1 max-w-xs">{orgAddress}</p>
                    )}
                    <p className="text-[9px] text-slate-400 mt-0.5">
                      {orgEmail} • {orgPhone} {orgGstin ? `• GSTIN: ${orgGstin}` : ""}
                    </p>
                  </div>
                </div>

                <div className="text-right shrink-0">
                  <span
                    style={{ background: selectedTemplate.primary_color || "#1e1b4b" }}
                    className="inline-block text-white text-[9px] font-black uppercase px-2.5 py-0.5 rounded tracking-wider mb-1"
                  >
                    Official Payslip
                  </span>
                  <p className="text-[10px] font-bold text-slate-700 dark:text-slate-300">
                    Period: {mockPayslip.month}/{mockPayslip.year}
                  </p>
                  <p className="text-[9px] font-mono text-slate-400">
                    REF: PAY-{mockPayslip.year}-{mockPayslip.month.toString().padStart(2, '0')}-{mockPayslip.id.slice(0, 6).toUpperCase()}
                  </p>
                </div>
              </div>

              {/* ─── Title Pill ─── */}
              <div className="text-center py-1.5 px-3 bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 rounded-lg text-xs font-bold uppercase tracking-wider mb-4 relative z-10 text-slate-800 dark:text-slate-200">
                Salary Certificate & Disbursal Slip
              </div>

              {/* ─── Employee Info Grid ─── */}
              <div className="grid grid-cols-2 gap-2 bg-slate-50/80 dark:bg-slate-800/40 border border-slate-200 dark:border-slate-700 rounded-lg p-3 mb-4 text-[11px] relative z-10">
                <div className="space-y-1">
                  <div className="flex justify-between">
                    <span className="text-slate-500 font-medium">Employee Name:</span>
                    <span className="font-bold text-slate-900 dark:text-white">{mockPayslip.employee_name}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-500 font-medium">Employee Code:</span>
                    <span className="font-mono font-bold text-slate-900 dark:text-white">{mockPayslip.employee_code}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-500 font-medium">Department:</span>
                    <span className="font-medium text-slate-700 dark:text-slate-300">{mockPayslip.department || "Corporate"}</span>
                  </div>
                </div>

                <div className="space-y-1">
                  <div className="flex justify-between">
                    <span className="text-slate-500 font-medium">Designation:</span>
                    <span className="font-semibold text-slate-800 dark:text-slate-200">{mockPayslip.designation || "Staff Specialist"}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-500 font-medium">Payment Status:</span>
                    <span
                      style={{ color: selectedTemplate.accent_color || "#16a34a" }}
                      className="font-bold"
                    >
                      {mockPayslip.status}
                    </span>
                  </div>
                  {selectedTemplate.show_bank_details && (
                    <div className="flex justify-between">
                      <span className="text-slate-500 font-medium">Payout Mode:</span>
                      <span className="font-medium text-slate-700 dark:text-slate-300">Direct Bank Remittance</span>
                    </div>
                  )}
                </div>
              </div>

              {/* ─── Earnings & Deductions Breakdown Table ─── */}
              <div className="border border-slate-200 dark:border-slate-700 rounded-lg overflow-hidden mb-4 relative z-10">
                <table className="w-full text-left text-[11px]">
                  <thead>
                    <tr
                      style={{ background: selectedTemplate.primary_color || "#1e1b4b" }}
                      className="text-white text-[10px] uppercase font-bold"
                    >
                      <th className="px-3 py-2 border-r border-white/20 w-1/2">Earnings (A)</th>
                      <th className="px-3 py-2 w-1/2">Deductions (B)</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="align-top divide-x divide-slate-200 dark:divide-slate-700">
                      {/* Earnings */}
                      <td className="p-3 space-y-1.5 bg-white dark:bg-slate-900">
                        <div className="flex justify-between">
                          <span className="text-slate-600 dark:text-slate-400">Basic Salary</span>
                          <span className="font-bold text-slate-900 dark:text-white">
                            {currency.symbol}{mockPayslip.basic_salary.toLocaleString()}
                          </span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-slate-600 dark:text-slate-400">House Rent (HRA)</span>
                          <span className="font-bold text-slate-900 dark:text-white">
                            {currency.symbol}{mockPayslip.hra.toLocaleString()}
                          </span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-slate-600 dark:text-slate-400">Special Allowances</span>
                          <span className="font-bold text-slate-900 dark:text-white">
                            {currency.symbol}{mockPayslip.other_allowances.toLocaleString()}
                          </span>
                        </div>
                        <div className="border-t border-slate-200 dark:border-slate-700 pt-1.5 flex justify-between font-extrabold text-slate-900 dark:text-white">
                          <span>Gross Earnings (A)</span>
                          <span>{currency.symbol}{mockPayslip.gross_salary.toLocaleString()}</span>
                        </div>
                      </td>

                      {/* Deductions */}
                      <td className="p-3 space-y-1.5 bg-white dark:bg-slate-900">
                        <div className="flex justify-between">
                          <span className="text-slate-600 dark:text-slate-400">Provident Fund (PF)</span>
                          <span className="font-bold text-red-600 dark:text-red-400">
                            {currency.symbol}{mockPayslip.pf_deduction.toLocaleString()}
                          </span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-slate-600 dark:text-slate-400">ESI Contribution</span>
                          <span className="font-bold text-red-600 dark:text-red-400">
                            {currency.symbol}{mockPayslip.esi_deduction.toLocaleString()}
                          </span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-slate-600 dark:text-slate-400">TDS / Income Tax</span>
                          <span className="font-bold text-red-600 dark:text-red-400">
                            {currency.symbol}{mockPayslip.tds_deduction.toLocaleString()}
                          </span>
                        </div>
                        <div className="border-t border-slate-200 dark:border-slate-700 pt-1.5 flex justify-between font-extrabold text-slate-900 dark:text-white">
                          <span>Total Deductions (B)</span>
                          <span className="text-red-600 dark:text-red-400">
                            {currency.symbol}
                            {(mockPayslip.pf_deduction + mockPayslip.esi_deduction + mockPayslip.tds_deduction + mockPayslip.other_deductions).toLocaleString()}
                          </span>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>

              {/* ─── Net Salary Disbursed Box ─── */}
              <div className="bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-300 dark:border-emerald-800 rounded-xl p-3 sm:p-4 flex items-center justify-between mb-5 relative z-10">
                <div>
                  <div
                    style={{ color: selectedTemplate.accent_color || "#15803d" }}
                    className="text-xs font-black uppercase tracking-wider"
                  >
                    Net Salary Disbursed (A - B)
                  </div>
                  <p className="text-[10px] text-emerald-700 dark:text-emerald-400 italic mt-0.5">
                    Transferred electronically to registered salary account
                  </p>
                </div>
                <div
                  style={{ color: selectedTemplate.accent_color || "#15803d" }}
                  className="text-xl sm:text-2xl font-black"
                >
                  {currency.symbol}{mockPayslip.net_salary.toLocaleString()}
                </div>
              </div>

              {/* ─── Signatory Section ─── */}
              {selectedTemplate.show_signatures && (
                <div className="flex justify-between items-end pt-3 border-t border-dashed border-slate-300 dark:border-slate-700 mt-4 relative z-10 text-[10px]">
                  <div className="w-2/5">
                    <div className="h-6 border-b border-slate-800 dark:border-slate-300 mb-1" />
                    <div className="font-bold text-slate-900 dark:text-white">
                      {selectedTemplate.left_signatory_title || "Employee Acknowledgment"}
                    </div>
                    <div className="text-slate-400 text-[9px]">{mockPayslip.employee_name}</div>
                  </div>

                  <div className="w-2/5 text-right">
                    <div className="h-6 border-b border-slate-800 dark:border-slate-300 mb-1" />
                    <div className="font-bold text-slate-900 dark:text-white">
                      {selectedTemplate.right_signatory_title || "Authorized Signatory"}
                    </div>
                    <div className="text-slate-400 text-[9px]">Payroll Operations • {orgName}</div>
                  </div>
                </div>
              )}

              {/* ─── Footer Strip ─── */}
              <div className="mt-4 pt-2 border-t border-slate-200 dark:border-slate-700 flex justify-between text-[9px] text-slate-400 relative z-10">
                <div>{selectedTemplate.footer_notes || "System Generated Electronic Salary Certificate"}</div>
                <div>{orgName} • Confidential Record</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
